# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79f83e9873412066a801a4f851d7c29c60a12ef2ed218c5061fe4f80580cb600ec01d9a4413581863c24cf7089e7dfc739339bbfe166fa48810726afa88444e4

test:
  secret_key_base: 77f199628ffcd04ff663ec77c4b9a7123cc46277075af58996ea00903c522ba37ca384384c9660c98fe24ddcf9a8ad132ce207a8bb23b9b04f6aa9570d7a6b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
